   # Official Tomcat image use karo
   FROM tomcat:10.1-jdk21

   # Default webapps hatao
   RUN rm -rf /usr/local/tomcat/webapps/*

   # Apna WAR file copy karo (target folder se)
   COPY target/CompanyWebAppNew.war /usr/local/tomcat/webapps/ROOT.war

   # Port 8080 expose karo
   EXPOSE 8080